import type { QuestDefinition, QuestState } from "./questTypes";

export const QUEST_DEFINITIONS: readonly QuestDefinition[] = [
  {
    id: "quest-floor-1-prehistory",
    title: "조선의 건국과 발전",
    summary: "루나와 함께 던전 1층의 정체를 조사하자.",
    description: "던전 안의 주민과 살아 움직이는 역사의 정체를 파악한다.",
    objectiveText: "던전 1층 마지막 방 조사",
    giverNpcId: "theo",
    turnInNpcId: "kaiden",
    offerStorySequenceId: "npc-theo-floor-1-quest-available",
    acceptStorySequenceId: "npc-theo-floor-1-quest-accepted",
    activeStorySequenceId: "npc-theo-floor-1-quest-active",
    targetFloorId: "floor-1",
    completeStorySequenceId: "npc-aron-floor-1-quest-complete",
    rewards: { description: "10 Gold" },
  },
  {
    id: "quest-floor-2-memory-fragment",
    title: "유교 질서에 따른 조선 사회의 모습",
    summary: "던전 2층의 혼란을 해결하고 수상한 물건을 회수하자.",
    description: "유교 질서의 단서를 모아 던전 2층의 혼란을 해결한다.",
    objectiveText: "던전 2층 단서 3개 수집 및 마지막 방 조사",
    giverNpcId: "luna",
    turnInNpcId: "kaiden",
    offerStorySequenceId: "npc-luna-floor-2-quest-available",
    acceptStorySequenceId: "npc-luna-floor-2-quest-accepted",
    activeStorySequenceId: "npc-luna-floor-2-quest-active",
    targetFloorId: "floor-2",
    completeStorySequenceId: "npc-aron-floor-2-quest-complete",
    rewards: { description: "7 Gold · 양반의 부채(희귀)" },
  },
  {
    id: "quest-floor-3-torn-cloth",
    title: "던전 3층 조사",
    summary: "던전 3층에서 느껴지는 기운을 조사하자.",
    description: "루나가 감지한 수상한 기운을 따라 던전 3층을 조사하고 단서를 가져온다.",
    objectiveText: "던전 3층 조사",
    giverNpcId: "luna",
    offerStorySequenceId: "npc-luna-floor-3-quest-available",
    acceptStorySequenceId: "npc-luna-floor-3-quest-accepted",
    activeStorySequenceId: "npc-luna-floor-3-quest-active",
    targetFloorId: "floor-3",
    completeStorySequenceId: "npc-luna-floor-3-quest-complete",
    rewards: { description: "5 Gold · 광개토대왕 갑옷(희귀)" },
  },
  {
    id: "quest-floor-4-jeon-rescue",
    title: "수상한 것의 정체",
    summary: "던전 4층 너머의 수상한 것을 찾자.",
    description: "던전 3층의 천 조각과 닮은 기운을 따라 던전 4층 너머를 조사한다.",
    objectiveText: "던전 4층 너머의 수상한 것 찾기",
    giverNpcId: "luna",
    offerStorySequenceId: "npc-luna-floor-4-quest-available",
    acceptStorySequenceId: "npc-luna-floor-4-quest-accepted",
    activeStorySequenceId: "npc-luna-floor-4-quest-active",
    targetFloorId: "floor-4",
    completeStorySequenceId: "npc-luna-floor-4-quest-complete",
    rewards: { description: "5 Gold · 칠지도 무기 스킨(희귀)" },
  },
  {
    id: "quest-floor-5-unified-silla", title: "삼국 통일의 과정", summary: "던전 5층을 동료들과 조사하자.",
    description: "전쟁터처럼 변한 던전 5층을 함께 조사하고 다음 층으로 향하는 통로를 연다.",
    objectiveText: "던전 5층의 닫힌 입구 열기", giverNpcId: "theo",
    offerStorySequenceId: "npc-theo-floor-5-quest-available", acceptStorySequenceId: "npc-theo-floor-5-quest-accepted",
    activeStorySequenceId: "npc-theo-floor-5-quest-active", targetFloorId: "floor-5",
    completeStorySequenceId: "npc-theo-floor-5-quest-complete",
    rewards: { description: "5 Gold · 문무왕의 갑옷(희귀)" },
  },
  {
    id: "quest-floor-6-balhae",
    title: "길 잃은 발해의 혼",
    summary: "전과 함께 던전 6층의 목소리를 조사하자.",
    description: "던전 6층에서 정체를 잃은 발해 유민들의 혼을 돕고 다음 층의 길을 연다.",
    objectiveText: "발해 유민들의 정체 찾기",
    giverNpcId: "kaiden",
    offerStorySequenceId: "npc-kaiden-floor-6-quest-available",
    acceptStorySequenceId: "npc-kaiden-floor-6-quest-accepted",
    activeStorySequenceId: "npc-kaiden-floor-6-quest-active",
    targetFloorId: "floor-6",
    completeStorySequenceId: "npc-kaiden-floor-6-quest-complete",
    rewards: { description: "10 Gold · 신라의 환두대도(희귀)" },
  },
  {
    id: "quest-floor-7-goryeo-founding",
    title: "고려의 기둥",
    summary: "전과 함께 던전 7층에서 호족의 증표를 모으자.",
    description: "던전 7층의 문을 가로막은 수수께끼를 풀고 고려의 기둥을 바로 세운다.",
    objectiveText: "호족의 증표 3개를 모아 문 열기",
    giverNpcId: "theo",
    offerStorySequenceId: "npc-theo-floor-7-quest-available",
    acceptStorySequenceId: "npc-theo-floor-7-quest-accepted",
    activeStorySequenceId: "npc-theo-floor-7-quest-active",
    targetFloorId: "floor-7",
    completeStorySequenceId: "npc-theo-floor-7-quest-complete",
    rewards: { description: "5 Gold · 궁예의 안대(희귀)" },
  },
  {
    id: "quest-floor-8-goryeo-relations",
    title: "고려와 주변 국가의 관계",
    summary: "동료들과 던전 8층 안쪽에서 단서를 찾자.",
    description: "고려와 주변 국가의 관계를 보여주는 단서를 조사하고 마지막 방의 비석을 완성한다.",
    objectiveText: "던전 8층의 고려 역사 비석 조사",
    giverNpcId: "kaiden",
    offerStorySequenceId: "npc-kaiden-floor-8-quest-available",
    acceptStorySequenceId: "npc-kaiden-floor-8-quest-accepted",
    activeStorySequenceId: "npc-kaiden-floor-8-quest-active",
    targetFloorId: "floor-8",
    completeStorySequenceId: "npc-kaiden-floor-8-quest-complete",
    rewards: { description: "5 Gold · 고려 최무선 화포(희귀)" },
  },
  {
    id: "quest-floor-9-goryeo-society-culture",
    title: "고려시대의 사회와 문화",
    summary: "던전 9층에서 고려시대 사회와 문화의 증거를 모으자.",
    description: "고려시대의 사회와 문화를 나타내는 증거 3개를 모아 10층 문 앞의 제단에 올려놓는다.",
    objectiveText: "고려시대 사회·문화의 증거 3개 수집",
    giverNpcId: "luna",
    offerStorySequenceId: "npc-luna-floor-9-quest-available",
    acceptStorySequenceId: "npc-luna-floor-9-quest-accepted",
    activeStorySequenceId: "npc-luna-floor-9-quest-active",
    targetFloorId: "floor-9",
    completeStorySequenceId: "npc-luna-floor-9-quest-complete",
    rewards: { description: "20 Gold · 팔만대장경(희귀)" },
  },
  {
    id: "quest-floor-10-final-source",
    title: "포탈의 원흉",
    summary: "던전 10층에서 포탈의 원흉과 마주하자.",
    description: "마지막 층의 문 너머로 들어가 포탈을 만든 원흉을 확인한다.",
    objectiveText: "던전 10층의 보스방 진입",
    giverNpcId: "kaiden",
    offerStorySequenceId: "npc-kaiden-floor-10-quest-available",
    acceptStorySequenceId: "npc-kaiden-floor-10-quest-accepted",
    activeStorySequenceId: "npc-kaiden-floor-10-quest-active",
    targetFloorId: "floor-10",
    rewards: { description: "보스 전투 준비 중" },
  },
];

export const INITIAL_QUEST_STATE: QuestState = Object.fromEntries(
  QUEST_DEFINITIONS.map((quest, index) => [
    quest.id,
    index === 0 ? "available" : "locked",
  ]),
);
